version: '3.8'

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    ports:
      - "5432:5432"
    volumes:
      - ./axelor-data/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - axelor-network

  axelor-app:
    image: kapsiki/kapsiki-mgm-dev:latest-v8.4.3
    container_name: axelor-app
    depends_on:
      - db
    environment:
      AXELOR_CONFIG_DB_DEFAULT_URL: jdbc:postgresql://db:5432/axelor
      AXELOR_CONFIG_DB_DEFAULT_USER: axelor
      AXELOR_CONFIG_DB_DEFAULT_PASSWORD: axelor
      AXELOR_CONFIG_DATA_UPLOAD_DIR: /opt/axelor/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./axelor-data/uploads:/opt/axelor/uploads 
    networks:
      - axelor-network

networks:
  axelor-network:
    driver: bridge
